version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.8.0
  - dependency-name: gatsby-plugin-styled-components
    versions:
    - 3.8.0
  - dependency-name: xmldom
    versions:
    - 0.4.0
  - dependency-name: got
    versions:
    - 11.8.0
- package-ecosystem: npm
  directory: "/badge-maker"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
